### PR TITLE
Add a static function to return a UserProperty with the name and value already defined

### PR DESCRIPTION
**Pull request by FabianoLothor**

### CODE REVIEW

**Comment by aawnu** [comment]
I do not agree that this is a big enough convenience to add in the library compared to a local helper function when it only saves you from chaining 2 methods. `UserPropertu::make($name,$value)` compared to `UserProperty::new()->setName($name)->setValue($value)`.

You can make a helper function in your local code, something alike:

```php
function makeUserProperty(string $name, int|float|string $value) {
    return UserProperty::new()->setName($name)->setValue($value);
}
```

Does this make sense?

**Comment by FabianoLothor** [comment]
Well, yeah, I already implemented that in my code base.

Just thought that would be useful for others to have it in the library.

```php
    return UserProperty::make($name, $value);
    // or as you suggested
    return makeUserProperty($name, $value);

    // At least for me is much more clear and clean than
    return UserProperty::new()->setName($name)->setValue($value);
```

Specially considering that we are using that in the middle of a builder.

```php
GoogleAnalyticsService::new(..., ...)
  ->addUserProperty(UserProperty::new()->setName($name)->setValue($value))
  ->addEvent(...)
  ->post();
```

Ideally I would prefer to just pass the `$name` and `$value` to the `addUserProperty` method above and the method would take care of the rest (I'm doing that in my code base).

But I didn't want to add changes that would break previous versions of the library, that's why I came with the `make` method.

```php
// The following code is at least readable

GoogleAnalyticsService::new(..., ...)
  ->addUserProperty(UserProperty::make($nameX, $valueY))
  ->addUserProperty(UserProperty::make($nameX, $valueY))
  ->addEvent(...)
  ->post();

// To make the current approach readable I need to do the following:

$userPropertyA = UserProperty::new()->setName($nameX)->setValue($valueY);
$userPropertyB = UserProperty::new()->setName($nameX)->setValue($valueY);
...
GoogleAnalyticsService::new(..., ...)
  ->addUserProperty($userPropertyA)
  ->addUserProperty($userPropertyB)
  ->addUserProperty($userProperty...)
  ->addEvent(...)
  ->post();
```

**Comment by aawnu** [comment]
I understand your approach, however, the following is neither a clean code solution nor quickly readable as you need to go through each step to fully understand what is happening.

```php
// ...
$analytics = GoogleAnalytics::new($id, $secret)
    ->setClientId($client)
    ->addUserProperty(UserProperty::make($name, $value))
// ...
```

Where as this quickly tells the user what is happening when and where.

```php
// ...
$prop = UserProperty::new()->setName($name)->setValue($value);

$analytics = GoogleAnalytics::new($id, $secret)
    ->setClientId($client)
    ->addUserProperty($prop)
// ...
```

Do bear in mind though that you can pass multiple user properties on the `addUserProperty` method as follows:

```php
// ...
    ->addUserProperty($propA, $propB, $propC)
// ...
    ->addUserProperty(...$arrayOfProps)
// ...
    ->addUserProperty(
        UserProperty::new()->setName($nameA)->setValue($valueA),
        UserProperty::new()->setName($nameB)->setValue($valueB),
        UserProperty::new()->setName($nameC)->setValue($valueC)
    )
// ...
```

**Comment by aawnu** [comment]
I am discussing this with a colleague and if you want a quicker approach, then you can add the properties as option to the constructor and then also the static new() method along these lines.

What do you think?

```php

__constructor(string $name = null, int|float|string $value) {
    if ($name !== null) {
        $this->name = $name;
    }
    if ($value!== null) {
        $this->name = $value;
    }
}

static function new(string $name = null, int|float|string $value) {
    return new static($name, $value);
}
```

**Comment by FabianoLothor** [comment]
The problem with that last approach is that breaks the code of previous versions, but for personal use, it's 100% fine.

It's almost the same thing I did with the `make` function, similar approach, except that now you can use the constructor.

The downside here is that I'm almost sure that in higher versions of PHP, you can't change the definition of a parent method, so you wouldn't be able to change the `new` method definition.

> Where as this quickly tells the user what is happening when and where.
> 
> ```
> // ...
> $prop = UserProperty::new()->setName($name)->setValue($value);
> 
> $analytics = GoogleAnalytics::new($id, $secret)
>     ->setClientId($client)
>     ->addUserProperty($prop)
> // ...
> ```

I would agree if we were talking about a single user property, but imagine 20 lines of properties. before the `GoogleAnalytics::new`, so that more 20 lines of `addUserProperty`.

Do bear in mind though that you can pass multiple user properties on the addUserProperty method as follows:

// ...
    ->addUserProperty($propA, $propB, $propC)
// ...
    ->addUserProperty(...$arrayOfProps)
// ...
    ->addUserProperty(
        UserProperty::new()->setName($nameA)->setValue($valueA),
        UserProperty::new()->setName($nameB)->setValue($valueB),
        UserProperty::new()->setName($nameC)->setValue($valueC)
    )
// ...

That's nice, I think the version of the library I'm running doesn't have that, `v1.0.10`.

---

Anyway, I don't think we are moving forward here, I'm closing the PR, thank you for the feedback.

**Pull request closed without merging**
